# O PLANO DE DESENHO CONSISTE DE DOIS EIXOS ONDE X AUMENTA PARA DIREITA E DIMINUI PARA ESQUERDA, E O Y AUMENTO PARA BAIXO E DIMINUI PARA CIMA, O INVERSO DO PLANO CARTESIANO, SENDO A AREA VISIVEL DA TELA UM ESPAÇO QUE PARTE DE DO PONTO X=0 E Y=0 NO TOPO ESQUERDO DA TELA ATÉ O TAMANHO DETERMINADO NO COMANDO: 

# PYGAME.DISPLAY.SET_MODE((X,Y))

